# Generated by Django 5.2.10 on 2026-04-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('Host', 'host'), ('User', 'user')], default='User', max_length=10),
        ),
    ]
