# Generated by Django 5.2.10 on 2026-04-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('host', 'Host'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
