# Generated by Django 5.2.10 on 2026-05-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_host_approved',
            field=models.BooleanField(default=False),
        ),
    ]
